### ISSUE TITLE
Allow URI templates in paths

### ISSUE THREAD

**Issue by dselivanov** [dselivanov/RestRserve#10]
[RFC6570](https://tools.ietf.org/html/rfc6570) and test suite https://github.com/uri-templates/uritemplate-test/tree/8014d2561706bfec7fd27a7465ff3f957381427c

**Comment by artemklevtsov** [comment]
Нашёл реализацию похожего функционала в пакете `routr`: https://github.com/thomasp85/routr/blob/master/R/route.R#L273

**Comment by artemklevtsov** [comment]
Plumber related code: https://github.com/trestletech/plumber/blob/master/R/query-string.R

**Comment by artemklevtsov** [comment]
First try to make structure for the paths: https://gist.github.com/artemklevtsov/a158e6cac89dc43c454552d8a83249fd
We can separate exact, partial and regex paths and match its with same order.

**Comment by artemklevtsov** [comment]
Предложенный выше объект R6 предлагается использовать в `add_route`. При этом организацию обработчиков предлагаю изменить следующим образом:
- вместо схемы: `handlers$path$method` использовать `handlers$method$path`, что должно сократить область поиска
- При добавлении новых точек досутпа в `handlers$method` сначала добавлять точки с методом `exact`, в самый конец с методов `regex` - `partial` между ними.

**Comment by artemklevtsov** [comment]
Если будет просадка по производительности, то для точного соответствия можно исопльзовать `fastmatch` (нет зависимостей), а для `regex` `ore` (нет зависимостей).

**Comment by artemklevtsov** [comment]
Думается надо запилить отдельный `R6Class` для хранения и обработки путей, которые будет инициализирован для каждого метода в `handlers[[method]]`. Все пути можно разделить на 3 группы: 
- Точный (exact). Для этих путей мы ищем точное соответствие с помощью `==` + `which`. Ограничение: не должен оканчиваться на `/`.
- Частичный (partial). Для этих путей ищем частичное соответствие с помощью `startsWith` или аналогов (желательна параллельная проверка множества паттернов). Ограничение: должен оканчиваться на `/`.
- Шаблон (regex). Для этих путей ищем с помощью `stri_detect_regex_first` или аналогов (желательна параллельная проверка множества паттернов). Переменные задаются в фигурных скобках (`{var}`). После разбора переменных формируется `data.frame` с названием переменной, типов данных (указывается через `:` и заменятеся на `character` в случае отсутствия) и позиция в пути от корня.
Класс должен содержать метод `add_path` и `match_path`.
Для сведения поиска по регуляркам к минимуму предалаегтся сначала искать частичное соответствие. Для примера в пути `/weather/{city}` сначала проверить `startsWith(path, "/weather/")` и в случае успеха `stri_detect_regex_first(path, "/weather/[^\]/?$")`
Замечание: пакет `re2r` можео принимать несколько регулярок и гоняет их с помощью `RcppParallel`.
Вопросы:
- На что заменять названия переменных при генерации регулярных выражения. Текущий вариант - `[^/]`.
- Могут ли совпадать пути в exact и partial или при добавление бросаем ошибку? Например, `/status` и `/status/`.
- Могут ли совпадать префиксы путей для partial и regex или при добавлении бросаем ошибку? Например: `/weather/` и `/weather/{city}`.

**Comment by artemklevtsov** [comment]
> Могут ли совпадать префиксы путей для partial и regex или при добавлении бросаем ошибку? Например: `/weather/` и `/weather/{city}`.
Думаю, ответ должен быть такой. Префикс `/weather/` должен интерпретироваться как `/weather/.+$` и является более общим случаем `/weather/[^/]+/?$`. Поэтому вариант `/weather/[^/]+/?$` должен проверяться в первую очередь.

**Comment by artemklevtsov** [comment]
#34 should fix it.
