### ISSUE TITLE
Improve swagger-ui integration

### ISSUE THREAD

**Issue by artemklevtsov** [dselivanov/RestRserve#19]
`swagger` package contains obsolete swagger-ui version.

- [x] - move swagger files to `RestRserve` and remove `swagger` dependency
- [x] - refactor `write_swagger_ui_index_html`: move `index_html` to file in `inst/`
- [x] - refactor `RestRserveApplication$add_swagger_ui` to use internal swagger files

**Comment by dselivanov** [comment]
I don't think this is good idea to bundle all the swagger assets to RestRserve - this static files are quite heavy and I'm not sure we want to have them under version control. It may be better to send PR to https://github.com/rstudio/swagger and ask for update (I did it last time in December  - https://github.com/rstudio/swagger/pull/3).

**Comment by artemklevtsov** [comment]
Another way to download swagger-iu from the git-repo when use `add_swagger_ui`.

**Comment by artemklevtsov** [comment]
Closed by #35.
