### ISSUE TITLE
Ошибка при запрос с параметром URL без значения

### ISSUE THREAD

**Issue by artemklevtsov** [dselivanov/RestRserve#24]
Не увеерн, что такое поведение корректно.

```bash
curl 'https://localhost:5000/api/rating?clientid=123456&step
Error in query[[key]] : subscript out of bounds
```

**Comment by artemklevtsov** [comment]
```HTTP/1.1 500 Evaluation error
Connection: close
Content-type: text/plain```

**Comment by dselivanov** [comment]
К сожалению это ошибка в Rserve - вот какой получается распаршенная query string
>  Named chr [1:2] "123456" "step"
> - attr(*, "names")= chr [1:2] "clientid" ""

Хотя по идее я бы ожидал что-то вроде

> Named chr [1:2] "123456" NA
> - attr(*, "names")= chr [1:2] "clientid" "step"

Я исправлю это в RestRserve, но по идее нужно зарепортить в Rserve.
