### ISSUE TITLE
request hangs with no error - serving xgboost model

### ISSUE THREAD

**Issue by martinbel** [dselivanov/RestRserve#26]
I've developed an API that serves 2 xgboost models and does some calculations with data.table. 
The problem is that the API basically hangs when running this line `xgb_preds = predict(model, data.matrix(d))`. There is no visible error nor traceback.

I've tried running the app a few times and it hangs when running the predict call to the xgboost models, I figure this out just printing the objects until nothing got printed. 

Here is the code, i've changed some of the names and removed the last part for privacy issues. BTW, thanks for the great package! 

```
source('foo.R')
source('baz.R')

library(RestRserve)
library(caret)
library(data.table)
library(ggplot2)
library(ISOweek)
library(zoo)
library(xgboost)
library(jsonlite)
library(Hmisc)

xgb_models <- list()
features <- list()
for(var in c("var1", "var2")){
   xgb_models[[var]] <- xgb.load(sprintf('model_%s', var))
   features[[var]] <- readRDS(sprintf('features_%s', var))
}

# read files
df1 = read_df1(path1)
df2 = readRDS(path2)
df3 = readRDS(path3)

df4 = readRDS("pricing/data/df4.rds")
df4[, allowed_miles:=ifelse(allowed_miles > 3100, 3500, allowed_miles)]
df4[, month:=month(pkup_dt)]


str(input)
# http://localhost:8001/endpoint?p1=M7991&p2=M1521&p3=2018-01-05&p4=2&p5=2017-12-15

foo <- function(request, response){
   input <- list(p1=request$query[['p1']],
                 p2=request$query[['p2']],
                 p3=as.Date(request$query[['p3']], format="%Y-%m-%d"),
                 p4=as.numeric(request$query[['p4']]),
                 p5=as.Date(request$query[['p5']], format="%Y-%m-%d"))

   print(str(input))

   # Estimate competitor rates
   data = list()
   variables = c("var1", "var2")
   for(var in variables){
      extra_vars = c("var1_miles", "var1_days")
      ignore_vars = c("var2_days")
      
      flow_cols = c("grp1", "grp2")
      ftr = features[[var]]
      dt_in = parse_inputs(input)
      dt_in = read_df2(dt_in, extra_vars, df2)
      dt_in = merge(dt_in, df1, by=flow_cols)
      
      bycols = c(flow_cols, 'ym_size_name', "wday", extra_vars)
      dt_in = merge(dt_in, ftr[, setdiff(names(ftr), ignore_vars), with=F], by=bycols)
      
      d = dt_in[, get_feature_names(extra_vars), with=FALSE]
      print(data.matrix(d)) # this gets printed
      model = xgb_models[[var]] 
      xgb_preds = predict(model, data.matrix(d))  #### the API hangs here!!! 
      print("foo") # this doesn't get printed
      print(xgb_preds)
      d[, est_rate:=xgb_preds]
      print(d)    
      data[[var]] <- d
      print(data[[var]])
   }

   #some more code that never gets executed.


   response$body = toJSON(result)
   response$content_type = "application/json"
   response$headers = character(0)
   response$status_code = 200L
   forward()
}


# create application
app = RestRserve::RestRserveApplication$new()

# register endpoints and corresponding R handlers
app$add_get(path = "/endpoint", FUN = foo)
app$run(http_port = "8001")

```

**Comment by artemklevtsov** [comment]
Can you share an application logs or provide a small reproducible example of code?

**Comment by martinbel** [comment]
The logs don't say much more than is explained, that's why I don't see what else I can change from my end. I can't provide a reproducible example. 
I can print objects up to this line: xgb_preds = predict(model, data.matrix(d)).

**Comment by artemklevtsov** [comment]
@dselivanov provides example with xgboost (see https://github.com/dselivanov/RestRserve/tree/master/examples/xgboost-mushrooms) which works fine.
Try to dump the `data.matrix(d)`  in your loop and analyze it later. Also try to write logs within `foo`.

**Comment by martinbel** [comment]
Another point. If I run the code interactively, simulating the request it works fine. 
I took a look at the xgboost example, what I've done is similar. I even tried loading the model inside the foo() call which didn't work. 
data.matrix(d) looks just fine to me.

**Comment by martinbel** [comment]
Finally, if i include all the code that is in the global environment inside foo(), the API works. 
These objects are 3 data.table objects and a list with MASS:rlm models that are loaded at the start of the script df1, df2, df3, etc.

**Comment by dselivanov** [comment]
I doubt this is something to do with RestRserve. Please provide **minimal** reproducible example, otherwise it is hard to help.

**Comment by martinbel** [comment]
ok, I'll try to set it up.

**Comment by martinbel** [comment]
I was able to solve the issue by replacing the data.table file read with data.table::fread by an RDS file. I'm not sure how this had anything to do but it works now. Perhaps it helps others in a similar case.

**Comment by dselivanov** [comment]
It seems this was related to #28 and https://github.com/microsoft/LightGBM/issues/2217. The issue is that openmp threads don't work correctly from with a fork.

**Comment by dselivanov** [comment]
I suspect it would work if you specify to use 1 thread in `fread`

**Comment by martinbel** [comment]
I don't know why this would be a problem but after removing the fread calls and replacing these by readRDS there were no issues.
