### ISSUE TITLE
structured errors

### ISSUE THREAD

**Issue by dselivanov** [dselivanov/RestRserve#29]
Starting from R 3.6.0 we can use structured errors - `errorCondition`. So middleware and handlers could easily raise errors which will be caught in a single place - `RestRserveApplication`.  This will greatly simplify and streamline logic and will allow to remove `forward()`, `interrupt()` calls.

**Comment by dselivanov** [comment]
because we will be using `checkmate` (which depends on `backports`) - we can relax requirement of R>=3.6 and use `backports:: errorCondition` -  https://github.com/r-lib/backports/blob/master/NEWS.md#backports-114

**Comment by artemklevtsov** [comment]
Now merged to `dev`.
