### ISSUE TITLE
RestRserveRequest methods

### ISSUE THREAD

**Issue by dselivanov** [dselivanov/RestRserve#36]
Check what ideas we can borrow: 
- [reqres::request](https://github.com/thomasp85/reqres/blob/master/R/request.R)
- [falcon request](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#id1)

**Comment by artemklevtsov** [comment]
I will plan move `parse_request` to `RestRserveRequest` constructor.
- cookies field.
- `request_id` must be moved to the active bindings to protect it.
- `set_param`/`has_param`/`delete_param` for the query.
- `set_header`/`has_header`/`delete_header` for the headers.
- `set_cookie`/`has_cookie`/`delete_cookie` for the cookies.
- `set_body`
- `set_content_type`
- `accept` field.
- `encoding` field.

**Comment by dselivanov** [comment]
> I will plan move parse_request to RestRserveRequest constructor.
 Not sure about that. But you can try to propose something. Just keep development of this particular feature in a separate branch, so we can proceed with the rest of functionality independently.

**Comment by artemklevtsov** [comment]
Sure. Major changes require more testing and review.
`parse_request` now used only in `http_request`. `parse_request` now used as preconstructor for the `RestRserveRequest`. I have not any reasons to hold this in the separate functions which wrap one another.

**Comment by artemklevtsov** [comment]
Should we rename `query` public field to `params`?

**Comment by artemklevtsov** [comment]
> If an HTML form is POSTed to the API using the application/x-www-form-urlencoded media type, Falcon can automatically parse the parameters from the request body and merge them into the query string parameters.
